name: Build and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: dotnet publish -c Release --output ./Release
    - name: Sync files to hosting
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: 178.154.231.185
        username: ${{ secrets.FTP_LOGIN }}
        password: ${{ secrets.FTP_PASSWORD }}
